# Generated by Django 5.1.7 on 2025-05-30 06:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='medical_history',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
