# Generated by Django 5.1.7 on 2025-06-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('completed', 'Đã khám'), ('canceled', 'Đã hủy')], default='unpaid', max_length=20),
        ),
    ]
