# Generated by Django 5.1.7 on 2025-04-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='file',
        ),
    ]
