# Generated by Django 5.1.7 on 2025-04-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
