# Generated by Django 5.1.7 on 2025-05-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorinfo',
            options={},
        ),
    ]
