# Generated by Django 5.1.7 on 2025-04-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
