# Generated by Django 5.1.7 on 2025-04-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_testresult_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='health_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinic.healthrecord'),
            preserve_default=False,
        ),
    ]
