# Generated by Django 5.1.7 on 2025-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_healthrecord_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='disease_type',
            field=models.TextField(choices=[('HoHap', 'Đường hô hấp'), ('TieuHoa', 'Đường tiêu hoá'), ('TK_TT', 'Thần kinh - Tâm thần'), ('Mat', 'Bệnh về Mắt'), ('ChanThuong', 'Chấn thương - chỉnh hình'), ('DaLieu', 'Da liễu'), ('TaiMuiHong', 'Tai - Mũi - Họng'), ('Khac', 'Khác')], max_length=20),
        ),
    ]
