# Generated by Django 5.1.7 on 2025-06-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_message_test_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent_message',
        ),
    ]
