# Generated by Django 5.1.7 on 2025-05-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_appointment_doctor_and_more'),
        ('clinic', '0003_appointment_cancel_reason_and_more'),
    ]

    operations = [
    ]
