# Generated by Django 5.1.7 on 2025-06-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_appointment_status'),
        ('clinic', '0003_remove_message_parent_message'),
    ]

    operations = [
    ]
