# Generated by Django 5.1.7 on 2025-05-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_phone',
            field=models.CharField(default=98, max_length=11),
            preserve_default=False,
        ),
    ]
