# Generated by Django 5.1.7 on 2025-04-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_patient_gender_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birthday',
            new_name='day_of_birth',
        ),
    ]
