# Generated by Django 5.1.7 on 2025-05-08 08:18

import ckeditor.fields
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_merge_20250503_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=ckeditor.fields.RichTextField(default='Chưa có thông tin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1745596143/thuk5xmnliibjcabjyw7.png', max_length=255),
            preserve_default=False,
        ),
    ]
