# Generated by Django 5.1.7 on 2025-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_user_number_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
