# Generated by Django 5.1.7 on 2025-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('completed', 'Đã khám'), ('cancelled', 'Đã hủy')], default='unpaid', max_length=20),
        ),
    ]
