# Generated by Django 5.1.7 on 2025-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_hospital_description_hospital_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
