# Generated by Django 5.1.7 on 2025-06-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
