# Generated by Django 5.1.7 on 2025-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_patient_day_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
