# Generated by Django 5.1.7 on 2025-05-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_user_number_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='cccd',
            field=models.CharField(default=123, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
