# Generated by Django 5.1.7 on 2025-04-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_doctor_license_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlot',
            new_name='Schedule',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time_slot',
            new_name='schedule',
        ),
    ]
