# Generated by Django 5.1.7 on 2025-05-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_healthrecord_cccd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='cccd',
            new_name='CCCD',
        ),
    ]
