# Generated by Django 5.1.7 on 2025-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_rename_cccd_healthrecord_cccd'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='BHYT',
            field=models.CharField(default=8304001234, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
