# Generated by Django 5.1.7 on 2025-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_healthrecord_bhyt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='medical_history',
            field=models.TextField(null=True),
        ),
    ]
