# Generated by Django 5.1.7 on 2025-06-09 07:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
