# Generated by Django 5.1.7 on 2025-05-13 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_healthrecord_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
