# Generated by Django 5.1.7 on 2025-05-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_alter_healthrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_date',
        ),
    ]
