# Generated by Django 5.1.7 on 2025-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_remove_user_active_remove_user_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
