# Generated by Django 5.1.7 on 2025-05-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_alter_healthrecord_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorInfo',
            new_name='Doctor',
        ),
    ]
