# Generated by Django 5.1.7 on 2025-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_rename_doctorinfo_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=100000, help_text='Giá khám bệnh (VND)', max_digits=10),
        ),
    ]
