# Generated by Django 5.1.7 on 2025-05-26 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_doctor_consultation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='healthrecord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinic.healthrecord'),
            preserve_default=False,
        ),
    ]
