# Generated by Django 5.1.7 on 2025-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_remove_appointment_user_appointment_healthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='sum_booking',
            field=models.IntegerField(default=0),
        ),
    ]
