# Generated by Django 5.1.7 on 2025-05-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_schedule_sum_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_available',
        ),
    ]
