# Generated by Django 5.1.7 on 2025-05-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_alter_appointment_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('healthrecord', 'schedule')},
        ),
    ]
