# Generated by Django 5.1.7 on 2025-05-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rescheduled_from',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
